CREATE TABLE AUTHOR (ID NUMERIC(19) NOT NULL, date_of_birth VARCHAR(255) NULL, first_name VARCHAR(50) NULL, last_name VARCHAR(50) NULL, preferred_Language VARCHAR(255) NULL, PRIMARY KEY (ID))
CREATE TABLE MUSICIAN (ID NUMERIC(19) NOT NULL, date_of_birth VARCHAR(255) NULL, first_name VARCHAR(50) NULL, last_name VARCHAR(50) NULL, preferred_instrument VARCHAR(255) NULL, PRIMARY KEY (ID))
CREATE TABLE SEQUENCE (SEQ_NAME VARCHAR(50) NOT NULL, SEQ_COUNT NUMERIC(28) NULL, PRIMARY KEY (SEQ_NAME))
INSERT INTO SEQUENCE(SEQ_NAME, SEQ_COUNT) values ('SEQ_GEN', 0)
